name: VenZ
channels:
  - conda-forge
  - bioconda
dependencies:
  - ipykernel
  - beautifulsoup4
  - ca-certificates
  - openssl
  - requests
  - pandas
  - certifi
  - pdfplumber
  - tqdm
  - matplotlib
  - openai
  - pinecone
  - datasets
  - ipywidgets
  - seaborn
  - scikit-learn
  - openpyxl